apiVersion: apps/v1
kind: Deployment
metadata:
    name: my-deployment
    labels:
      app: chatroom
spec:
   template:
      metadata:
        labels:
           app: chatroom
      spec:
         containers:
            - name: myapp-container
              image: manjuappu1375/chat_room
              ports:
               -  containerPort: 8080
              volumeMounts:
                - mountPath: "/mnt/chatroom-data"
                  name: chatroom-storage
         volumes:
           - name: chatroom-storage
             persistentVolumeClaim:
               claimName: chatroom-pvc
   selector:
      matchLabels:
         app: chatroom
   replicas: 3