apiVersion: v1
kind: PersistentVolume
metadata:
  name: chatroom-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: chatroom-storage-class
  hostPath:
    path: /mnt/chatroom-data