apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chatroom-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: chatroom-storage-class